spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_application_db
    username: root
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update